import numpy as np

synthetic_txt = 'Synthetic test data, not representative of actual events.'

samples = {}

samples['template'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6'},
    'dimensions': [('time', 1),
                   ('lat', 1),
                   ('lon', 1)],
    'variables': {
        'dummy': {'create_args': {'datatype': 'f4',
                                  'dimensions': ('time', 'lat', 'lon'),
                                  'zlib': True,
                                  'chunksizes': None},
                  'attributes': {'units': 1,
                                 'standard_name': 'dummy_variable'},
                  # 'random':  [0,1), 'gradient' [0,1], 'pairing'
                  'fill_mode': None,
                  'values': 0,
                  # Used in fill_mode, NOT a NetCDF scale_factor
                  'data_scale_factor': 1.0,
                  # Used in fill_mode, NOT a NetCDF add_offset
                  'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': None,
    'level_values': None,
    'lon_values': None,
    'lat_values': None}

samples['no_time_no_location'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6'},
    'dimensions': [],
    'variables': {
        'dummy': {'create_args': {'datatype': 'f4',
                                  'dimensions': (),
                                  'zlib': True,
                                  'chunksizes': None},
                  'attributes': {'units': 1,
                                 'standard_name': 'dummy_variable'},
                  'fill_mode': None,
                  'values': 42,
                  'data_scale_factor': 1.0,
                  'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': None,
    'level_values': None,
    'lon_values': None,
    'lat_values': None}

samples['one_time_no_location'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('time', 1)],
    'variables': {
        'tas': {'create_args': {'datatype': 'f4',
                                'dimensions': ('time', ),
                                'zlib': True,
                                'chunksizes': None},
                'attributes': {'units': 'K',
                               'standard_name': 'air_temperature'},
                'fill_mode': None,
                'values': 287.0,
                'data_scale_factor': 1.0,
                'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': None,
    'level_values': None,
    'lon_values': None,
    'lat_values': None}

samples['timeseries_no_location'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('time', 365)],
    'variables': {
        'tas': {'create_args': {'datatype': 'f4',
                                'dimensions': ('time', ),
                                'zlib': True,
                                'chunksizes': None},
                'attributes': {'units': 'K',
                               'standard_name': 'air_temperature'},
                'fill_mode': 'pairing',
                'data_scale_factor': 1.0,
                'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': None,
    'level_values': None,
    'lon_values': None,
    'lat_values': None}

samples['timeseries_no_location_mf_1'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('time', 365)],
    'variables': {
        'tas': {'create_args': {'datatype': 'f4',
                                'dimensions': ('time', ),
                                'zlib': True,
                                'chunksizes': None},
                'attributes': {'units': 'K',
                               'standard_name': 'air_temperature'},
                'fill_mode': 'pairing',
                'data_scale_factor': 1.0,
                'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': np.arange(0, 365),
    'level_values': None,
    'lon_values': None,
    'lat_values': None}
samples['timeseries_no_location_mf_2'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('time', 365)],
    'variables': {
        'tas': {'create_args': {'datatype': 'f4',
                                'dimensions': ('time', ),
                                'zlib': True,
                                'chunksizes': None},
                'attributes': {'units': 'K',
                               'standard_name': 'air_temperature'},
                'fill_mode': 'pairing',
                'data_scale_factor': 1.0,
                'data_add_offset': 365.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': np.arange(365, 730),
    'level_values': None,
    'lon_values': None,
    'lat_values': None}
samples['timeseries_no_location_mf_3'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('time', 365)],
    'variables': {
        'tas': {'create_args': {'datatype': 'f4',
                                'dimensions': ('time', ),
                                'zlib': True,
                                'chunksizes': None},
                'attributes': {'units': 'K',
                               'standard_name': 'air_temperature'},
                'fill_mode': 'pairing',
                'data_scale_factor': 1.0,
                'data_add_offset': 730.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': np.arange(730, 1095),
    'level_values': None,
    'lon_values': None,
    'lat_values': None}

samples['no_time_regular_lon_lat'] = {
    'nc_format': 'NETCDF4_CLASSIC',
    'global_attributes': {'Conventions': 'CF-1.6',
                          'comment': synthetic_txt},
    'dimensions': [('lat', 179), ('lon', 360)],
    'variables': {
        'elevation': {'create_args': {'datatype': 'f4',
                                      'dimensions': ('lat', 'lon'),
                                      'zlib': True,
                                      'chunksizes': None},
                      'attributes': {'units': 'm',
                                     'standard_name': 'ground_level_altitude'},
                      'fill_mode': 'pairing',
                      'data_scale_factor': 1.0,
                      'data_add_offset': 0.0}
        },
    'time_num_values': 1,
    'time_dtype': 'i2',
    'time_units': 'days since 2001-01-01 00: 00: 00',
    'time_calendar': 'gregorian',
    'level_dtype': 'f4',
    'level_units': 'm',
    'level_positive': 'up',
    'level_name': 'height',
    'time_values': None,
    'level_values': None,
    'lon_values': None,
    'lat_values': None}
