import numpy as np

# Naming shortcuts
# s{time_frequency}{grid_type}{id}[_#]
# time_frequecy = 00 (none), wd (windows), yy (annual), mm (monthly),
#                 dd (daily), hh(hourly), sd (subdaily), ot (other)
# grid_type = 00 (none), st (stations), rl (regular lon lat), ir (irregular)
#             cu (custom)
# id = 2 digits id
# [-#] for data in multiple files (optional)
# e.g. sddrl01-1

samples = {}

samples['template'] = {
    'nc_format':'NETCDF4_CLASSIC',
    'global_attributes':{},
    'use_time':True,
    'use_level':False,
    'use_lat':False,
    'use_lon':False,
    'use_station':False,
    'use_ycxc':False,
    'time_size':1,  # None for UNLIMITED, or same as time_num_values
    'time_num_values':1,
    'level_size':1,
    'lat_size':1,
    'lon_size':1,
    'station_size':1,
    'yc_size':1,
    'xc_size':1,
    'time_dtype':'i2',
    'time_units':'days since 2001-01-01 00:00:00',
    'time_calendar':'gregorian',
    'level_dtype':'f4',
    'level_units':'Pa',
    'level_positive':'down',
    'var_name':'dummy',
    'var_dtype':'f4',
    'var_units':'1',
    'var_standard_name':'dummy_variable',
    'data_scale_factor':1.0,  # Used in fill_mode, NOT a NetCDF scale_factor
    'data_add_offset':0.0,  # Used in fill_mode, NOT a NetCDF add_offset
    'fill_mode':None,  # 'random': [0,1), 'gradient' [0,1], 'pairing'
    'time_values':None,
    'lon_values':None,
    'lat_values':None,
    'var_values':0}

samples['no_time_no_location'] = {
    'nc_format':'NETCDF4_CLASSIC',
    'use_time':False,
    'use_level':False,
    'use_lat':False,
    'use_lon':False,
    'use_station':False,
    'use_ycxc':False,
    'time_size':1,
    'time_num_values':1,
    'level_size':1,
    'lat_size':1,
    'lon_size':1,
    'station_size':1,
    'yc_size':1,
    'xc_size':1,
    'time_dtype':'i2',
    'time_units':'days since 2001-01-01 00:00:00',
    'time_calendar':'gregorian',
    'level_dtype':'f4',
    'level_units':'Pa',
    'level_positive':'down',
    'var_name':'dummy',
    'var_dtype':'f4',
    'data_scale_factor':1.0,
    'data_add_offset':0.0,
    'fill_mode':None,
    'time_values':None,
    'lon_values':None,
    'lat_values':None,
    'var_values':42}


# One time, no location
s000001 = {'nc_format':'NETCDF4_CLASSIC',
           'use_time':True,
           'use_level':False,
           'use_lat':False,
           'use_lon':False,
           'use_station':False,
           'use_ycxc':False,
           'time_size':1,  # None for UNLIMITED, or same as time_num_values
           'time_num_values':1,
           'level_size':1,
           'lat_size':1,
           'lon_size':1,
           'station_size':1,
           'yc_size':1,
           'xc_size':1,
           'time_dtype':'i2',
           'time_units':'days since 2001-01-01 00:00:00',
           'time_calendar':'gregorian',
           'level_dtype':'f4',
           'level_units':'Pa',
           'level_positive':'up',
           'var_name':'dummy',
           'var_dtype':'f4',
           'data_scale_factor':1.0,
           'data_add_offset':0.0,
           'fill_mode':None,
           'time_values':None,
           'lon_values':None,
           'lat_values':None,
           'var_values':42}

# Time array, no location
sdd0001 = {'nc_format':'NETCDF4_CLASSIC',
           'use_time':True,
           'use_level':False,
           'use_lat':False,
           'use_lon':False,
           'use_station':False,
           'use_ycxc':False,
           'time_size':31,  # None for UNLIMITED, or same as time_num_values
           'time_num_values':31,
           'level_size':1,
           'lat_size':1,
           'lon_size':1,
           'station_size':1,
           'yc_size':1,
           'xc_size':1,
           'time_dtype':'i2',
           'time_units':'days since 2001-01-01 00:00:00',
           'time_calendar':'gregorian',
           'level_dtype':'f4',
           'level_units':'Pa',
           'level_positive':'up',
           'var_name':'dummy',
           'var_dtype':'f4',
           'data_scale_factor':1.0,
           'data_add_offset':0.0,
           'fill_mode':None,
           'time_values':None,
           'lon_values':None,
           'lat_values':None,
           'var_values':np.arange(0,365)}

# Time array, over multiple files
sdd0002_1 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':False,
             'use_lon':False,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':1,
             'lon_size':1,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':None,
             'time_values':np.arange(0,365),
             'lon_values':None,
             'lat_values':None,
             'var_values':np.arange(0,365)*10}
sdd0002_2 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':False,
             'use_lon':False,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':1,
             'lon_size':1,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':None,
             'time_values':np.arange(365,730),
             'lon_values':None,
             'lat_values':None,
             'var_values':np.arange(365,730)*10}
sdd0002_3 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':False,
             'use_lon':False,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':1,
             'lon_size':1,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':None,
             'time_values':np.arange(730,1095),
             'lon_values':None,
             'lat_values':None,
             'var_values':np.arange(730,1095)*10}

# No time, regular lon lat
s00rl01 = {'nc_format':'NETCDF4_CLASSIC',
           'use_time':False,
           'use_level':False,
           'use_lat':True,
           'use_lon':True,
           'use_station':False,
           'use_ycxc':False,
           'time_size':1,  # None for UNLIMITED, or same as time_num_values
           'time_num_values':1,
           'level_size':1,
           'lat_size':179,
           'lon_size':360,
           'station_size':1,
           'yc_size':1,
           'xc_size':1,
           'time_dtype':'i2',
           'time_units':'days since 2001-01-01 00:00:00',
           'time_calendar':'gregorian',
           'level_dtype':'f4',
           'level_units':'Pa',
           'level_positive':'up',
           'var_name':'dummy',
           'var_dtype':'f4',
           'data_scale_factor':1.0,
           'data_add_offset':0.0,
           'fill_mode':'pairing',
           'time_values':None,
           'lon_values':None,
           'lat_values':None,
           'var_values':None}

# No time, irregular lon lat
s00ir01 = {'nc_format':'NETCDF4_CLASSIC',
           'use_time':False,
           'use_level':False,
           'use_lat':False,
           'use_lon':False,
           'use_station':False,
           'use_ycxc':True,
           'time_size':1,  # None for UNLIMITED, or same as time_num_values
           'time_num_values':1,
           'level_size':1,
           'lat_size':1,
           'lon_size':1,
           'station_size':1,
           'yc_size':170,
           'xc_size':192,
           'time_dtype':'i2',
           'time_units':'days since 2001-01-01 00:00:00',
           'time_calendar':'gregorian',
           'level_dtype':'f4',
           'level_units':'Pa',
           'level_positive':'up',
           'var_name':'dummy',
           'var_dtype':'f4',
           'data_scale_factor':1.0,
           'data_add_offset':0.0,
           'fill_mode':'pairing',
           'time_values':None,
           'lon_values':None,
           'lat_values':None,
           'var_values':None}

# Daily time array, regular lon lat
sddrl01 = {'nc_format':'NETCDF4_CLASSIC',
           'use_time':True,
           'use_level':False,
           'use_lat':True,
           'use_lon':True,
           'use_station':False,
           'use_ycxc':False,
           'time_size':365,  # None for UNLIMITED, or same as time_num_values
           'time_num_values':365,
           'level_size':1,
           'lat_size':179,
           'lon_size':360,
           'station_size':1,
           'yc_size':1,
           'xc_size':1,
           'time_dtype':'i2',
           'time_units':'days since 2001-01-01 00:00:00',
           'time_calendar':'gregorian',
           'level_dtype':'f4',
           'level_units':'Pa',
           'level_positive':'up',
           'var_name':'dummy',
           'var_dtype':'f4',
           'data_scale_factor':1.0,
           'data_add_offset':0.0,
           'fill_mode':'pairing',
           'time_values':None,
           'lon_values':None,
           'lat_values':None,
           'var_values':None}

# Time array, over multiple files, regular lon lat grid
sddrl02_1 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':True,
             'use_lon':True,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':179,
             'lon_size':360,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':'pairing',
             'time_values':np.arange(0,365),
             'lon_values':None,
             'lat_values':None,}
sddrl02_2 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':True,
             'use_lon':True,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':179,
             'lon_size':360,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':'pairing',
             'time_values':np.arange(365,730),
             'lon_values':None,
             'lat_values':None}
sddrl02_3 = {'nc_format':'NETCDF4_CLASSIC',
             'use_time':True,
             'use_level':False,
             'use_lat':True,
             'use_lon':True,
             'use_station':False,
             'use_ycxc':False,
             'time_size':365,  # None for UNLIMITED, or same as time_num_values
             'time_num_values':365,
             'level_size':1,
             'lat_size':179,
             'lon_size':360,
             'station_size':1,
             'yc_size':1,
             'xc_size':1,
             'time_dtype':'i2',
             'time_units':'days since 2001-01-01 00:00:00',
             'time_calendar':'gregorian',
             'level_dtype':'f4',
             'level_units':'Pa',
             'level_positive':'up',
             'var_name':'dummy',
             'var_dtype':'f4',
             'data_scale_factor':1.0,
             'data_add_offset':0.0,
             'fill_mode':'pairing',
             'time_values':np.arange(730,1095),
             'lon_values':None,
             'lat_values':None}
    
